# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_core/protos/service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'grpc_core/protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_core/protos/service.proto\x12\x07traffic\"@\n\x13\x43ustomerTrafficInfo\x12\x14\n\x0c\x43ustomerName\x18\x01 \x01(\t\x12\x13\n\x0bTrafficsSum\x18\x02 \x01(\x02\"A\n\x0fTrafficResponse\x12.\n\x08Traffics\x18\x01 \x03(\x0b\x32\x1c.traffic.CustomerTrafficInfo\"O\n\x0eTrafficRequest\x12\x12\n\nCustomerID\x18\x01 \x01(\x05\x12\x0e\n\x06\x42\x65\x66ore\x18\x02 \x01(\t\x12\r\n\x05\x41\x66ter\x18\x03 \x01(\t\x12\n\n\x02IP\x18\x04 \x01(\t2L\n\x07Traffic\x12\x41\n\nGetTraffic\x12\x17.traffic.TrafficRequest\x1a\x18.traffic.TrafficResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_core.protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERTRAFFICINFO']._serialized_start=43
  _globals['_CUSTOMERTRAFFICINFO']._serialized_end=107
  _globals['_TRAFFICRESPONSE']._serialized_start=109
  _globals['_TRAFFICRESPONSE']._serialized_end=174
  _globals['_TRAFFICREQUEST']._serialized_start=176
  _globals['_TRAFFICREQUEST']._serialized_end=255
  _globals['_TRAFFIC']._serialized_start=257
  _globals['_TRAFFIC']._serialized_end=333
# @@protoc_insertion_point(module_scope)
