version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8008:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash -c 'gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker main:app'
